### ISSUE TITLE
Update stable version in repo from 0.0.0 to 0.1.2

### ISSUE THREAD

**Issue by GermanBluefox** [xXBJXx/ioBroker.tractive-gps#2]
# Think about adding version 0.1.2 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**0.1.2** (152 days old)
**Installs**: stable=**0** (0%), latest=**11** (68.75%), total=**16**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

**Comment by mcm1957** [comment]
Is there any reason to delay publishing at stable repository?

If there is no reaction here within 30 days we will evaluate to publish it anyway.

If you need any help, please let us know.

**Comment by mcm1957** [comment]
Link to forum:
https://forum.iobroker.net/topic/53903/tractive-adapter-f%C3%BCr-haustiere/141

**Comment by mcm1957** [comment]
@xXBJXx 
Is there any reason to delay publishing at stable repository?

If there is no reaction here within 14 days we will evaluate to publish it anyway.

If you need any help, please let us know.

**Comment by mcm1957** [comment]
wait for #4 feedback
Poll sent at telegram too

**Comment by mcm1957** [comment]
OUTDATED
